### ISSUE TITLE
Bug: Sqlite driver throws error when writing some escaped characters in create command

### ISSUE THREAD

**Issue by TimeBather** [shigma/minato#14]
When `ctx.database.create` inputs a  escaped characters , the sqlite driver throws a error:
```js
await ctx.database.create("problem_test",{
    test:"example1''"
  })
```
Error:
```
app Error: unrecognized token: "\"
                            at f.handleError (D:\koishi-projects\koishi-opensource-development\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
                            at f.prepare (D:\koishi-projects\koishi-opensource-development\node_modules\@minatojs\sql.js\dist\sql-wasm.js:90:46)
                            at SQLiteDriver.#exec (D:\koishi-projects\koishi-opensource-development\node_modules\@minatojs\driver-sqlite\src\index.ts:204:28)
                            at SQLiteDriver.#run (D:\koishi-projects\koishi-opensource-development\node_modules\@minatojs\driver-sqlite\src\index.ts:231:5)
```

**Comment by shigma** [comment]
此问题是因为 sqlite 对单引号的转义方式与 mysql 不一致。现已修复。
