### ISSUE TITLE
数据库查表SQL语法出错

### ISSUE THREAD

**Issue by lgc2333** [shigma/minato#29]
```
[W] sqlite > SELECT  FROM `channel` ywyvinvk WHERE `platform` = 'onebot' AND `id` = '1105946125'
2023-07-17 23:42:05 [W] session /translate good
                        Error: near "FROM": syntax error
                            at f.handleError (C:\bot\koishi\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
                            at f.prepare (C:\bot\koishi\node_modules\@minatojs\sql.js\dist\sql-wasm.js:90:46)
                            at #exec (C:\bot\koishi\node_modules\@minatojs\driver-sqlite\lib\index.js:351:26)
                            at #all (C:\bot\koishi\node_modules\@minatojs\driver-sqlite\lib\index.js:363:48)
                            at SQLiteDriver.get (C:\bot\koishi\node_modules\@minatojs\driver-sqlite\lib\index.js:286:54)
                            at Selection.execute (C:\bot\koishi\node_modules\@minatojs\core\lib\index.cjs:385:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _DatabaseService.getChannel (C:\bot\koishi\node_modules\@koishijs\core\lib\index.cjs:394:18)
                            at async _Session.getChannel (C:\bot\koishi\node_modules\@koishijs\core\lib\index.cjs:2080:21)
                            at async _Session._observeChannelLike (C:\bot\koishi\node_modules\@koishijs\core\lib\index.cjs:2105:18)
```

**Comment by shigma** [comment]
这是 translate 插件的问题。你检查下 translate 插件用的是哪一个，有没有更新？

**Comment by lgc2333** [comment]
> 这是 translate 插件的问题。你检查下 translate 插件用的是哪一个，有没有更新？

plugin used is `koishi-plugin-open-translate`, depends `"@koishijs/translator": "^1.0.0"`

**Comment by shigma** [comment]
> ###
> [Jul 18, 2023](#issuecomment-1640002252)

那你可以让这个插件作者去更新一下依赖。
